---
- name: Setting up web server
  hosts: localhost
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: yes  
    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
      become: yes
    - name: Configure Nginx
      copy:
       src: ./nginx/nginx.conf
       dest: /etc/nginx/nginx.conf
      become: yes
    - name: Additional Nginx Configuration
      copy:
        src: "{{ item }}"
        dest: /etc/nginx/snippets/
      with_fileglob:
        - /snippets/*
      become: yes
    - name: Test Configuration
      ansible.builtin.command: nginx -t

      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      become: yes

...