---
- name: Setting up PHP
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: php_version
      prompt: "Which version php do you want to install?"
      private: no
  tasks:
    - name: Add PHP repository
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
        state: present
      become: yes
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
    - name: Installing PHP {{php_version}}
      ansible.builtin.apt:
        name: "{{item}}"
        state: present
      loop:
        - php{{php_version}}
        - php{{php_version}}-common 
        - php{{php_version}}-mysql 
        - php{{php_version}}-xml
        - php{{php_version}}-xmlrpc 
        - php{{php_version}}-curl 
        - php{{php_version}}-gd 
        - php{{php_version}}-imagick 
        - php{{php_version}}-cli
        - php{{php_version}}-dev 
        - php{{php_version}}-imap 
        - php{{php_version}}-mbstring 
        - php{{php_version}}-soap 
        - php{{php_version}}-zip 
        - php{{php_version}}-intl
        - php{{php_version}}-fpm
      become: yes
    
    - name: Starting php{{php_version}}-fpm service ....
      service:
        name: php{{php_version}}-fpm
        state: started
        enabled: yes

    - name: Configuration tuning
      copy:
        src: ./php/php.ini
        dest: /etc/php/{{php_version}}/fpm/php.ini

    - name: Restarting service
      service:
        name: php{{php_version}}-fpm
        state: restarted

...